### ISSUE TITLE
I need your help regarding the action masking

### ISSUE THREAD

**Issue by minhlong94** [kronion/sb3-action-masking-demo#1]
Hi kronion, I am doing a project using SB3 as backbone and it requires action masking. Since it is not implemented yet, I see your PR currently works great (tested myself)! I need your help implementing this masking, since I want to compare multiple algorithms in the project but your PR currently limits to PPO. Do you mind communicating through email or Discord? My email is `removed` and the Discord account is `removed`.

Thanks for your time.

**Comment by kronion** [comment]
Hi @minhlong94. Apologies for the slow response. Glad to hear that the PR is working well for you!

I'd also like to see masking support for other algorithms. Unfortunately, I'm not in a position to work on that right now. I may try to work on a couple others after completing the PPO PR, but it's not a guarantee.

I'd be happy to try to point you in the right direction, though, if you'd like to take a crack at it yourself. In addition to the latest version of the PPO PR, there's one earlier version you might want to look at. I originally implemented some `Maskable` mixin classes that were meant to be used alongside SB3's core classes to create maskable subclasses: https://github.com/kronion/stable-baselines3-contrib/tree/eb593c89fc1fa0a280eebff7e4536611dedb8054

Here's an example of a mixin being used: https://github.com/kronion/stable-baselines3-contrib/blob/eb593c89fc1fa0a280eebff7e4536611dedb8054/sb3_contrib/ppo_mask/ppo_mask.py#L13

Ultimately that version was more complicated than the SB3 team wanted, but it may help you see more clearly where changes need to be made to support masking, since it duplicates less code (ie it borrowed methods from SB3's core classes whenever possible).

If you do end up working on your own implementations, feel free to drop a link to the repo in this thread, and I'll try to take a look if I have time. 🤞 

I removed your contact info from your message above, but I saved it on my end. I'll reach out if circumstances change.

Best of luck!
